### ISSUE TITLE
Features ideas and plans (i.e., TODO list)

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/report#2]
### General
- [ ] **coloured to_text**: Add colours in textual report
- [x] **report priors**: Extract and format priors from Bayesian models
- [x] **report algorithm**: Extract algorithm used (for Bayesian, sampling and sampling properties (chains, samples), for frequentist, OLS, ML and such?)

### Support
- [x] ANOVAs: depends on omega square in parameters
- [x] brms: depends on get_priors in parameters
- [x] lme4: depends on p values in parameters
- [ ] rstanarm: meanfield algorithm: depends on `find_algorithm()`.
- [x] `estimate` objects: means and contrasts
- [ ] ...

**Comment by strengejacke** [comment]
Might be of interest: https://crsh.github.io/papaja_man/

**Comment by DominiqueMakowski** [comment]
I've been following their development for quite a while, but the scope seems quite different for now (but future bridges between the two could make sense, as they are positioned at an even higher level (document formatting) than report)

**Comment by DominiqueMakowski** [comment]
Came across this [small but promising package](https://github.com/ddsjoberg/gtsummary). 

They have some interesting ideas and made me think of some possible improvements:

## Table legends

We could add a legend for report tables (consisting in the header chunk of the textual reports about model description), stored in the attributes, that we would display upon print.

## Sample size info

We need to find a way to nicely add information about the sample size, flexible enough to deal with random groups

## Factor levels and interactions formatting

We could better format factor levels and interactions:
  - For factor levels, the idea would be to 1) detect whether a parameter is a factor level or a variable. 2) If a factor level, find the parent variable. 3) Display Something like:
```
  - Sepal.Width has an effect of ...
  - For Species:
     - versicolor has an effect of ...
     - setosa has an effect of
``` 
Instead of 
```
  - Sepal.Width has an effect of ...
  - versicolor has an effect of ...
  - setosa has an effect of
```
However,  the above proposition becomes trickier when involved in interactions.

- For interactions, instead of having `Sepal.Width:versicolor`, print either something like:
```
- The interaction between Sepal.Width and versicolor has an effect of ...
```
or
```
- For interactions:
  - Sepal.Width:versicolor has an effect of ...
```
But how to deal with interactions of interactions (e.g. `Sepal.Length:Petal.Width:versicolor`)?

**Comment by GegznaV** [comment]
Please, add functionality to report **Cramer's V** (and possibly other association measures for categorical variables). Here are some ideas on how Cramer's V could be reported:
http://rcompanion.org/handbook/H_10.html

**Comment by DominiqueMakowski** [comment]
@GegznaV It's noted, although we can't promise this feature anytime soon :) 

@strengejacke As it is a very small function (see [here](https://www.r-bloggers.com/example-8-39-calculating-cramers-v/)), we could potentially include it in performance?

**Comment by strengejacke** [comment]
There's a function in sjstats, [xtab_statistics()](https://strengejacke.github.io/sjstats/reference/xtab_statistics.html), that calculates various statistics for contigency tables. There are also two functions that compute Cramer's V and Phi coefficient. CIs for Cramer are probably based on [bootstrapping](https://github.com/strengejacke/sjstats/issues/69)? Must look into DescTools.

I don't see Cramer's V as a function for performance, but rather parameters. Or another package that computes "various statistics", like Cronbach's Alpha etc?

**Comment by DominiqueMakowski** [comment]
Right, `parameters` seems more appropriate (until/if we create a better place for it).

**Comment by DominiqueMakowski** [comment]
Closing this for now, so we can start fresh
